### ISSUE TITLE
가중치는 어떻게 결정되는 것인가요?

### ISSUE THREAD

**Issue by gregSHF** [icepeng/oriental-salad#13]
현재는 hsreplay에서 계산하고 있는 값을 그대로 가져와서 쓰는 것인가요?

**Comment by icepeng** [comment]
현재는 https://hsreplay.net/api/v1/archetypes/52/ 해당 api에서 제공되는 값을 사용합니다.

다만 현재 목적에 100% 적합한 자료가 아니라 다른 방법을 시도하는 중입니다.
