### ISSUE TITLE
카드평가 평가와 비교

### ISSUE THREAD

**Issue by gregSHF** [icepeng/oriental-salad#14]
1. 카드를 아주 많이 평가하지 않은 평가에 대해서도
평가한 카드들의 일반적인 정답률과, 표준편차등을 고려해
얼마나 잘 맞추었는지 대략적이라도 알려줬으면 좋겠습니다.

2. 평가 몇개를 골라 서로 비교할 수 있었으면 좋겠습니다.
누가 더 잘 맞추었는지, 평가가 갈린 카드가 어떤건지(그래서 누가 맞았는지) 등등을 보여주면 좋겠습니다.

3. 오리엔탈 샐러드를 사용하지 않고 평가를 한 bj 등에 대해
유저가 지금이라도 그 내용을 입력하면 (물론 자의적 해석이 포함되겠죠) 통계에는 포함되지 않더라도
얼마나 맞추었고 다른 통계에 비추어 얼마나 잘 맞췄는지 확인할 수 있으면 좋겠습니다.
유저 개개인이 일일이 입력하려면 꽤 귀찮으니 그 결과를 공유 할 수 있으면 더 좋겠습니다.

**Comment by icepeng** [comment]
1. 적중률은 지금도 표본 수 상관없이 나오지 않나요?
2. 조금만 더 구체적인 스펙이 나오면 바로 작업 가능하겠네요.
3. 그건 좀... 얻는 기능에 비해 작업이 꽤 많아질거 같네요. 원하는 분들이 많다면 해보겠습니다.

**Comment by icepeng** [comment]
https://github.com/icepeng/oriental-salad/issues/15
